### ISSUE TITLE
📚 Documentation: Incorrect variable name 'result' or 'response' in the code snippet

### ISSUE THREAD

**Issue by naman1608** [appwrite/website#1022]
### 💭 Description

<img width="1255" alt="image" src="https://github.com/appwrite/website/assets/74304916/14ce990f-65c1-4388-8f9d-e35bd1af32b5">

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by shivanshukarn** [comment]
@naman1608 Can you share the link that which page of the documentation has this issue?

**Comment by stnguyen90** [comment]
@naman1608 thanks for creating this issue! 🙏🏼 This should be fixed now after https://github.com/appwrite/appwrite/issues/8328
