### ISSUE TITLE
📚 Documentation: Uncaught (in promise) AppwriteException: The current user is not authorized to perform the requested action.

### ISSUE THREAD

**Issue by Yondemon4266** [appwrite/website#1027]
### 💭 Description

When I have completed the tutorial "build an ideas tracker with React" https://appwrite.io/docs/tutorials/react/, I had errors on the client console saying that my authenticated User didn't have permission to perform the requested action.
But the thing is that we have to go on the database that we created and in the collection and give permissions to the user we are connected to to use and/or manipulate the database collection.

This is not mentionned in the tutorial.

Regards ! 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rogix** [comment]
I believe it's related to #139

**Comment by stnguyen90** [comment]
Yes, this should be fixed as part of https://github.com/appwrite/website/pull/1019
