### ISSUE TITLE
🚀 Enhancement: Use Pagination for Blog Posts

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/website#1038]
### 🔖 Enhancement description

The blog page has a lot of posts, all rendered on the same page, at once. For better performance, use pagination logic with something like -

```text
< Prev    1, 2, 3, 4    Next >
```

### 🎤 Pitch

Faster image and page loads, better performance.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rogix** [comment]
I agree. The blog page has serious performance issues. From what I can see, the main issue is the image sizes—they are huge.

**Evidence:**

By checking the page on PageSpeed Insights, we can see the low performance score:

**Mobile:**
<img src="https://github.com/appwrite/website/assets/12768403/98e93309-b647-4800-8077-c9cec4898bf4" width=400 />

**Desktop:**
<img src="https://github.com/appwrite/website/assets/12768403/3eba756f-d98e-459b-8ece-c3a23fd59771" width=400 />

[PageSpeed Insights Report](https://pagespeed.web.dev/analysis/https-appwrite-io-blog/fu73cdx8bu?form_factor=desktop)

By checking the loaded files on the `network` tab, we can identify one of the reasons: 

82 MB of resources (images) is quite significant. 

<img width="504" alt="image" src="https://github.com/appwrite/website/assets/12768403/4e4a1365-fd5e-4bc9-a3be-5f753ee1dc68">

---

**A few suggestions to fix the problem:**

1. **Use smaller image sizes from the beginning**
   - Many images don't need to be high resolutions. The higher the resolution, the larger the size. Low-resolution images are sufficient for most cases. There are some good websites that compress images for free.
   - Most images don't need to be very large in dimensions. Many images have widths over 2000px, but on the page, they are displayed at 700px or less. Reducing dimensions of the images could remove dozens of extra MBs.

2. **Use an image compression library to compress and reduce image sizes during the build process**
   - This is very straightforward. There are libraries that help compress images while maintaining good quality.

3. **Implement pagination as suggested**
   - I'm not sure if all the images are downloaded at once regardless of pagination, but if they are not, implementing pagination could significantly improve performance for everyone.

I might be missing something, but I think that implementing these simple techniques could be of great help. 

I would be glad to implement these improvements or discuss other alternatives if the friend @ItzNotABug hasn't already started working on this issue.

**Comment by Jacobojijo** [comment]
Solved this issue under PR #1174

**Comment by ItzNotABug** [comment]
Completed via - https://github.com/appwrite/website/pull/1152.
