### ISSUE TITLE
📚 Documentation: Update Community Office Hours

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/website#1107]
### 💭 Description

The office hours listed on [Community#UpcomingEvents](https://appwrite.io/community) are expired, completed. Either update them manually or use an automated logic to add dates of every next Thursday.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by adityaoberai** [comment]
@ItzNotABug I'll handle this

**Comment by adityaoberai** [comment]
Fixed in #1313
