### ISSUE TITLE
🐛 Bug Report: Function ID not found on requested deployment

### ISSUE THREAD

**Issue by kJAHsin** [appwrite/website#1161]
### 👟 Reproduction steps

Create a new function.
Added a new function to an exisiting repository. 
Navigated away after the first two steps (did not complete)

After this, the function is visible in the Appwrite console, but when I open it, the page displays the 404 error.

The function DOES have an ID, I can see it in the console. 

404 Deployment with the requested ID could not be found.

### 👍 Expected behavior

I would have imagined it should would have disposed of the unfinished function when exiting setup

### 👎 Actual Behavior

The function is "present" in console, but returns a 404 error when selecting

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kJAHsin** [comment]
Seems like it directly accessing the deployment when clicking the button to access the function.  This could be an oversite as, in this case, I didn't get that far.  only created the function

**Comment by stnguyen90** [comment]
@kJAHsin, thanks for raising this issue! 🙏🏼 Can you provide more exact steps to reproduce? I tried going through the wizard up to the last step:
<img width="1182" alt="image" src="https://github.com/user-attachments/assets/1d0c76a5-1700-42b4-b915-461f01336c45">
but the function doesn't create until you click Create.

Also, can you check the network logs for the get function API call? Does it have a value set for the deployment attribute?
