### ISSUE TITLE
🐛 Bug Report: Bad threads title encoding

### ISSUE THREAD

**Issue by Honzoraptor31415** [appwrite/website#1229]
### 👟 Reproduction steps

Go to (threads)[htttps://appwrite.io/threads], the first thread I see is this one:
![image](https://github.com/user-attachments/assets/0c583c92-c73e-4ef5-80f0-89529b768cbc)
and as you can see, the title's encoding is somehow messed up:
![image](https://github.com/user-attachments/assets/95c3a60d-27d2-4973-bf85-1edd442d77a0)
but on the thread page itself it's encoded normally again:
![image](https://github.com/user-attachments/assets/5e2c8dd4-9778-44fc-ab31-af0e58e8c481)

What's the weirdest is, that the encoding seems to be normal for like 600ms after the page has loaded, but then gets messed up.

### 👍 Expected behavior

The encoding should be working even in the threads feed

### 👎 Actual Behavior

The encoding doesn't work as expected in the the threads feed.

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
Closing as fixed in #1230.
