### ISSUE TITLE
📚 Documentation: Error in SvelteKit Tutorial Step 3

### ISSUE THREAD

**Issue by Mazahir26** [appwrite/website#136]
### 💭 Description

**Description**:

In the SvelteKit tutorial under step 3, there is a mistake in the code snippet provided. Specifically, the import statement for the Database and Account object is missing, and the appwrite module exports Databases instead of Database.

**Current code**:
```
import { Client } from "appwrite";

const client = new Client();
client
  .setEndpoint("https://cloud.appwrite.io/v1")
  .setProject("<YOUR_PROJECT_ID>"); // Replace with your project ID

export const account = new Account(client);
export const database = new Database(client);
```

**Suggested correction**:
```
import { Client, Databases, Account } from "appwrite"; // Added Databases & Account import

const client = new Client();
client
  .setEndpoint("https://cloud.appwrite.io/v1")
  .setProject("<YOUR_PROJECT_ID>");

export const account = new Account(client);
export const database = new Databases(client); // Changed to Databases
```

This adjustment ensures that the code functions as expected.

**Steps to Reproduce**:

1. Go to the SvelteKit tutorial step 3.
2. Follow the provided code snippet.

**Expected Behavior**:

The code provided should be accurate and functional.

**Additional Information**:

Documentation URL: [https://appwrite.io/docs/tutorials/sveltekit/step-3](https://appwrite.io/docs/tutorials/sveltekit/step-3)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by saiharsha-22** [comment]
Can i get this issue assigned to me ?

**Comment by Haimantika** [comment]
> Hello @Haimantika and @gewenyu99 Can i get this issue assigned to me ? I can work on this.

Hi @saiharsha-22 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by saiharsha-22** [comment]
Hello @Haimantika  and @gewenyu99  I have raised the pull-request for the following issue :- https://github.com/appwrite/website/pull/142 can you pls check it once.

**Comment by gewenyu99** [comment]
> Hello @Haimantika and @gewenyu99 I have raised the pull-request for the following issue :- #142 can you pls check it once. Can you add hacktoberfest label as i am participant of it. Thank you.

This will not be part of Hacktoberfest. But we're more than happy to receive your help ❤️ 

This year, only tasks marked as Hacktoberfest and opened by maintainers will be accepted as Hacktoberfest contributions. Thank you.
