### ISSUE TITLE
📚 Documentation: Arm64 support

### ISSUE THREAD

**Issue by SOG-web** [appwrite/website#1376]
### 💭 Description

trying to deploy to a arm64 server, am getting redis error, but I was able to fix, so am creating this issue so that i can reference it in a doc pull request

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@SOG-web, thanks for raising this issue! 🙏🏼 What error were you getting? It does look like there is an [arm64 variant of redis](https://hub.docker.com/layers/library/redis/7.2.4-alpine/images/sha256-642805a6784bf1d129b3a94378024c326af01d302b9f2bcbaba48d826240927f). Also, I just tested on an ARM64 instance of mine and I got Appwrite 1.6.0 working fine.

**Comment by SOG-web** [comment]
I was getting an error indicating that the default redis image cannot work on my server, so I just switch to a variant that supports arm64, and it worked

**Comment by SOG-web** [comment]
This is my server details

OS Information 	linux aarch64 Ubuntu 22.04.3 LTS
Kernel Version 	5.15.0-1045-oracle
Total CPU 	4
Total memory 	25.2 GB

Managed with `portainer`

**Comment by stnguyen90** [comment]
@SOG-web, 

> I was getting an error indicating that the default redis image cannot work on my server

Would you please share the exact error? And when exactly did you get the error? If it's just when running the container, you can test again by running `docker run --rm redis:7.2.4-alpine`, right?

> This is my server details

I have pretty much the same. 

OS Information linux aarch64 Ubuntu 22.04.3 LTS
Kernel Version 5.15.0-1049-oracle
Total CPU 4
Total memory 23.4 GB

And I didn't need to change my compose file.
