### ISSUE TITLE
📚 Documentation: Correct Mistakes in React tutorial in Docs

### ISSUE THREAD

**Issue by timDeHof** [appwrite/website#139]
### 💭 Description

As I worked through the React lesson and build the idea tracker, I found a few issues in the directions and code snippets.
 
1. The first issue I found was on the "Create app" page, the `npm create` command doesn't scaffold a Vite + React project correctly. Also code snippet might need two versions of it depending on the npm versions based on what I read in the [Vite Docs](https://vitejs.dev/guide/#scaffolding-your-first-vite-project).

2. The second issue I found was under the  "Initialize Appwrite SDK" heading on the "Set up Appwrite" page, where it states the wrong client, which needs to be corrected. As seen in the screenshot below.
![Screenshot 2023-09-30 at 1 51 21 PM](https://github.com/appwrite/website/assets/2568193/bbed2171-4ac1-4440-8264-db4365685e42)

3. The third issue I found was on the same page in the Appwrite related code that you can add to your `src/lib/appwrite.js` file. I believe now you are asked to import "Account" and "Databases" from "Appwrite" node.js module.
4. The fourth issue I found was in the `user.js` file on the "Add authentication" page, I believe the "create account" [endpoint](https://appwrite.io/docs/references/cloud/client-web/account#create) requires a unique `userId` string to go along with the "email" and "password".
5. The fifth issue I found was on the "add database" page  under the "Create collection" heading doesn't explain how adding user's permissions to the collection allows authorized user to view,create, or delete ideas.
        
![Screenshot 2023-09-30 at 2 44 24 PM](https://github.com/appwrite/website/assets/2568193/d08ca633-368a-46b1-92db-a68a76789ab8)

![Screenshot 2023-09-30 at 2 37 26 PM](https://github.com/appwrite/website/assets/2568193/447f0350-1156-42cd-b51f-80de33a728f4)
6. The sixth issue I found was that the lesson doesn't point out that you need update `src/App.jsx` by importing and adding the `IdeasProvider` component between the `main` element and `UserProvider` component. 
7. The seventh issue I found on the "Create ideas page" page, the code snippet used to overwrite the `src/pages/Home.jsx` code gives you an error saying the following:
![Screenshot 2023-09-30 at 3 24 33 PM](https://github.com/appwrite/website/assets/2568193/31eb1f54-a8ee-4f87-b164-fd7ae8d9fae9)

> **steps to Reproduce:**
>  1. Follow the React tutorial and add the code snippets along the way
>  2. `npm run dev -- --open --port 3000` to run the app
>  3. After registering, try to add an idea
8. The eighth issue I found on the "next steps" page, the clone link "this GitHub repository" isn't linked to a github repository of the completed version of the project. 
![Screenshot 2023-09-30 at 3 46 23 PM](https://github.com/appwrite/website/assets/2568193/6bb9ccf0-09d5-403f-b06a-6db21c74ecdf)

**Additional Information:** 
Documentation URL : [https://appwrite.io/docs/tutorials/react/step-1](https://appwrite.io/docs/tutorials/react/step-1)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Vishalk91-4** [comment]
@timDeHof, could you please assign this issue to me

**Comment by timDeHof** [comment]
I was kinda hoping to get it assigned to me. I was going to create a PR tomorrow for it.

**Comment by tessamero** [comment]
@gewenyu99 can you work with engineering to see if this can work for hacktoberfest labeled issue? If so, can you assign to timDeHof

**Comment by gewenyu99** [comment]
@timDeHof This won't a Hacktoberfest issue, but I've assigned it to you, more than happy to get your help!
