### ISSUE TITLE
🐛 Bug Report: Missing image in Flutter Documentation

### ISSUE THREAD

**Issue by Ghat0tkach** [appwrite/website#141]
### 👟 Reproduction steps

Step 1: Go to Appwrite's [Flutter](https://appwrite.io/docs/quick-starts/flutter) documentation
Step 2 : Scroll Down to the Add to Platform section

## The below image should be displayed in Add to Platform section
![image](https://github.com/appwrite/website/assets/59855919/dc934274-a4a6-4ed2-bbba-4310ef10899a)

### 👎 Actual Behavior

Current Behavior

![image](https://github.com/appwrite/website/assets/59855919/83692325-db5e-4d62-90da-074b3f6fff1b)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Ghat0tkach** [comment]
I would love to work on this issue 🙌⭐

**Comment by kanugurajesh** [comment]
I have checked the network on the website using browser and there is no response for add-platform.png image not even error and I have checked the image path on the website and it is working correctly

**Comment by Ghat0tkach** [comment]
Interesting , This wasnt working till yesterday . However this is working now 🤔
