### ISSUE TITLE
🚀 Enhancement: Update GitHub Star Count

### ISSUE THREAD

**Issue by tessamero** [appwrite/website#1439]
### 🔖 Enhancement description

Current website number: 43.9 
Today's stars: 44.3

### 🎤 Pitch

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gurjeetsinghvirdee** [comment]
The star count has reached **45K**, but the website does not reflect this because it does not update automatically due to the hardcoded value. Update the code to use this endpoint instead: `https://api.github.com/repos/appwrite/appwrite`
