### ISSUE TITLE
📚 Documentation: make correction in react tutorial

### ISSUE THREAD

**Issue by divijshrivastava** [appwrite/website#1445]
While following `Build an ideas tracker with React` tutorial, on step 7,  src/App.jsx has the following code

line 4: `import { IdeaProvider } from "./lib/context/ideas";`
line 12:         `<IdeaProvider>`
line 15:         `</IdeaProvider>`

which basically imports IdeaProvider from "./lib/context/ideas", but ideas.jsx does not export IdeaProvider, instead it exports `Idea**s**Provider`. Hence, this needs to be corrected.

**Comment by ernstmul** [comment]
Thanks for providing the PR. It's merged!
