### ISSUE TITLE
📚 Documentation: Incorrect links in the "Idea Tracker App" tutorial boxes on Quick Start Web page

### ISSUE THREAD

**Issue by Bakek-lang** [appwrite/website#1450]
### 💭 Description

The Quick Start documentation page https://appwrite.io/docs/quick-starts/web contains incorrect links under the section titled "Learn to use Appwrite by building an idea tracker app." There are four clickable boxes for different frameworks (React, Vue.js, Nuxt, SvelteKit), and each is intended to direct users to the "Idea Tracker App" tutorial for the respective framework. However, all the boxes currently link to the "Adding authentication to a simple web app" tutorial instead.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Bakek-lang, thanks for raising this issue! 🙏🏼 We'll fix this ASAP.
