### ISSUE TITLE
📚 Documentation: image doesnot exist 

### ISSUE THREAD

**Issue by suman-somu** [appwrite/website#146]
### 💭 Description

The git image is not showing on https://appwrite.io/docs/products/functions/deployment.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by suman-somu** [comment]
on it

**Comment by DerrickML** [comment]
the image is still not showing

**Comment by suman-somu** [comment]
let it be reviewed and merged

**Comment by DerrickML** [comment]
> let it be reviewed and merged

ohh.. Alright, thanks!
