### ISSUE TITLE
🐛 Bug Report: There is missing '/' closing tag in Auth implementation example in tutorials

### ISSUE THREAD

**Issue by Khushalsarode** [appwrite/website#1469]
### 👟 Reproduction steps

Here is details
Source path file: https://github.com/appwrite/website/blob/main/src/routes/docs/tutorials/react/step-7/%2Bpage.markdoc
 currently the code:

https://github.com/appwrite/website/blob/a151f19097da6533ef488af8a1306d85c732ef0b/src/routes/docs/tutorials/react/step-7/%2Bpage.markdoc#L91-L106

need to update is:
` </UserProvider> ` 

need the closing slash to remove error!

### 👍 Expected behavior

The code should not prompt error while following tutorials at path src/routes/docs/tutorials/react/step-7/+page.markdoc for implementing auth example for idea tracker. 

### 👎 Actual Behavior

Should Work fine after the correction is done!

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Code editor: VS code
Terminal: Windows Terminal
OS: windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Khushalsarode** [comment]
@stnguyen90

**Comment by stnguyen90** [comment]
@Khushalsarode, thanks for raising this issue! 🙏🏼 Would you like to submit a PR for this fix?
