### ISSUE TITLE
📚 Documentation: Error in React Tutorial Step 3

### ISSUE THREAD

**Issue by 000-KunalPal** [appwrite/website#150]
### 💭 Description

In the React tutorial under step 3, there is a mistake in the code snippet provided. Specifically, the export statement in line 9 exports database but in our step 7: Create ideas page, the import statement imports databases.

**Current code:**

```javascript
import { Client, Databases, Account } from "appwrite";

const client = new Client();
client
  .setEndpoint("https://cloud.appwrite.io/v1")
  .setProject("<YOUR_PROJECT_ID>"); // Replace with your project ID

export const account = new Account(client);
export const database = new Databases(client);

``` 

**Suggested correction:**
```javascript
import { Client, Databases, Account } from "appwrite";

const client = new Client();
client
  .setEndpoint("https://cloud.appwrite.io/v1")
  .setProject("<YOUR_PROJECT_ID>"); // Replace with your project ID

export const account = new Account(client);
export const databases = new Databases(client);

``` 
This adjustment ensures that the code functions as expected.

**Steps to Reproduce:**

1. Go to the SvelteKit tutorial step 3.
2. Follow the provided code snippet.

**Expected Behavior:**
The code provided should be accurate and functional.

**Additional Information:**
Documentation URL: [https://appwrite.io/docs/tutorials/react/step-3](url)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Gilbishkosma** [comment]
The same issue is in the step-3 of React, Vue and Svelte tutorial. Can i work on it?

**Comment by gewenyu99** [comment]
@Gilbishkosma Yes, you can work on it. I've assigned it to you.

**Comment by Gilbishkosma** [comment]
@gewenyu99 we can close this issue, as the PR has been merged.
