### ISSUE TITLE
🐛 Bug Report: Platform and Version Dropdowns Color in Dark Theme Needs Improvement

### ISSUE THREAD

**Issue by shaikahmadnawaz** [appwrite/website#168]
### 👟 Reproduction steps

1. Visit the Appwrite Databases Client Web Documentation https://appwrite.io/docs/references/cloud/client-web/databases page.
2. Toggle the website's theme to the dark theme if it's not already in dark mode.
3. Locate the platform and version dropdown menus, which should be near the top of the page.
4. Observe that the text color within the platform and version dropdown menus are difficult to read or has insufficient contrast against the dark background.

### 👍 Expected behavior

- When visiting the Appwrite Databases Client Web Documentation https://appwrite.io/docs/references/cloud/client-web/databases page in dark mode, the platform and version dropdown menus should have text color or background color that provides sufficient contrast and is easy to read against the dark background.
- Users should be able to select different platforms from the dropdown menu without any visibility issues.

### 👎 Actual Behavior

In the dark theme, the text color within the platform and version dropdown menus are challenging and hard for users to read and select.

![Screenshot 2023-10-03 004828](https://github.com/appwrite/website/assets/96189881/eb766faf-f712-4325-bc20-30ae1122c3dc)

![Screenshot 2023-10-03 005633](https://github.com/appwrite/website/assets/96189881/db6e155e-bbe0-4cec-bbce-9ecd3db7a867)

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by shaikahmadnawaz** [comment]
If this issue is considered valid, I am ready to take the initiative to resolve it. I am awaiting confirmation regarding its validity.

**Comment by stnguyen90** [comment]
@shaikahmadnawaz thanks for raising this issue! 🙏🏼 would you provide info about what browser you're using and the version?

**Comment by shaikahmadnawaz** [comment]
> @shaikahmadnawaz thanks for raising this issue! 🙏🏼 would you provide info about what browser you're using and the version?

Brave and its version is 1.58.135

**Comment by stnguyen90** [comment]
@shaikahmadnawaz, we pushed out a fix recently. Would you please clear your cache and share what you see now?

**Comment by shaikahmadnawaz** [comment]
> @shaikahmadnawaz, we pushed out a fix recently. Would you please clear your cache and share what you see now?

Yes, now everything is working fine @stnguyen90 

![image](https://github.com/appwrite/website/assets/96189881/0ee2dc67-d1b9-4ede-be7e-f2bc06421fd8)

**Comment by shaikahmadnawaz** [comment]
Shall I close this issue?
