### ISSUE TITLE
🐛 Bug Report: Back to Top Button Not Functioning as Expected

### ISSUE THREAD

**Issue by shaikahmadnawaz** [appwrite/website#169]
### 👟 Reproduction steps

1. Visit the documentation page https://appwrite.io/docs/references/cloud/client-web/databases
2. Scroll down the page to a section that requires scrolling.
3. Locate the "Back to Top" button, usually in the lower-right corner.
4. Click on the "Back to Top" button with the intention of returning to the top of the page.

### 👍 Expected behavior

Clicking on the "Back to Top" button should trigger a smooth scroll animation that returns the page to the top. This functionality enhances the user's experience by allowing them to easily navigate back to the top of the documentation page when they have scrolled down.

### 👎 Actual Behavior

Clicking on the "Back to Top" button does not result in the page scrolling back to the top. The functionality of the "Back to Top" button is currently not working as expected, which affects the user's ability to navigate the documentation efficiently.

![Screenshot 2023-10-03 011708](https://github.com/appwrite/website/assets/96189881/00092173-04bb-4881-a4e8-cce77fc73f94)

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by shaikahmadnawaz** [comment]
If this issue is considered valid, I am ready to take the initiative to resolve it. I am awaiting confirmation regarding its validity.

**Comment by shashankdaima** [comment]
Ayo @gewenyu99, I can take that.

**Comment by gewenyu99** [comment]
@shaikahmadnawaz @shashankdaima Can you hold off for some time? We're looking at this on our side.

**Comment by stnguyen90** [comment]
Fixed as part of https://github.com/appwrite/website/pull/262
