### ISSUE TITLE
📚 Documentation: Tutorial for Astro

### ISSUE THREAD

**Issue by Susmita-Dey** [appwrite/website#175]
### 💭 Description

**Goal**
Interactive tutorial for beginners to build their first functioning app using Astro and Appwrite.

**Content**
- The end product should be a functional app
- Step by step from setup. If there will be test data, provide a Server SDK script with instructions.
- Format should be similar to  /docs/tutorials/sveltekit
- Should contain the following content
  - install dependencies
  - make first request
  - implement auth
  - intro to databases
  - queries and paginations
  - storage (optional)
  - realtime (optional)
  - permissions (optional)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Susmita-Dey** [comment]
I would like to take it up and work on it.

**Comment by stnguyen90** [comment]
Closing as we have a [tutorial for astro](https://appwrite.io/docs/tutorials/astro-ssr-auth/step-1).
