### ISSUE TITLE
🐛 Bug Report: Go to Console Button Not Working in Docs page

### ISSUE THREAD

**Issue by ArnabBCA** [appwrite/website#176]
### 👟 Reproduction steps

1. Go to Docs Page
2. Switch to Mobile View
3. Open the Side bar

The **Bottom** Go to console button is not working it is not going to console page.
![Console](https://github.com/appwrite/website/assets/113178195/8e740589-83b7-47cc-8296-6c8e0b4a5f85)

Also there is two console button present which is not necessary. So we can just remove it

### 👍 Expected behavior

When The **Bottom** Go to console button is clicked it should navigate to console page

### 👎 Actual Behavior

The **Bottom** Go to console button is not working it is not going to console page.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ArnabBCA** [comment]
I would like to work in this issue

**Comment by Traveller08** [comment]
Can i work on it?

**Comment by ArnabBCA** [comment]
> Can i work on it?

Bro it's first come first serve kindly look for another issue

**Comment by shaurya-jain23** [comment]
I would like to work on this, please assign it to me

**Comment by guptadeepak8** [comment]
is this issue open to work ??

**Comment by TorstenDittmann** [comment]
@ArnabBCA feel free to provide a PR :-)

**Comment by ArnabBCA** [comment]
> @ArnabBCA feel free to provide a PR :-)

I know this doesn't make any sense but this issue was open in hacktoberfest is there any way you can label it hacktoberfest accepted😅

**Comment by ArnabBCA** [comment]
> @ArnabBCA feel free to provide a PR :-)

@TorstenDittmann I have opened the PR.
And this doesn't make sense but this Issue was opened during hacktoberfest is there any way you can add the hacktoberfest accepted label in the PR😅
