### ISSUE TITLE
📚 Documentation: Contribution Guide is missing

### ISSUE THREAD

**Issue by manipandit** [appwrite/website#177]
### 💭 Description

In README.md there is a contributing guide link which points to 404 - page not found.

![not found](https://github.com/appwrite/website/assets/110151059/9bb90569-5236-4cdb-8a80-f30956e4bca1)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by manipandit** [comment]
I would like to work on this.

**Comment by HimanshuTembhe** [comment]
Can you assign me this issue under hacktoberfest 2023 ?

**Comment by harshita1611** [comment]
Hey, I would like to work on this issue can you please assign it to me

**Comment by ayrotideysarkar** [comment]
Can I work on this @tessamero

**Comment by tessamero** [comment]
hi @ayrotideysarkar this is not a hacktoberfest issue, you can find it by searching the label hacktoberfest :) DM me if you need help on discord

**Comment by Haimantika** [comment]
Closing this issue as we have a Contributing Guide now - https://github.com/appwrite/website/blob/main/CONTRIBUTING.md
