### ISSUE TITLE
📚 Documentation: 

### ISSUE THREAD

**Issue by ravi0900** [appwrite/website#201]
### 💭 Description

**All changes made by taking care of all 4 breakpoints, (mobile, tab, laptop, desktop)**

**1. Updated Github Star Count 33.2 to 35.2**

**2. Few Letter Cases Changed to be more Professional**
a) Go to console -> Go to Console
b) Search in docs -> Search In Docs

I really want to contribute in appwrite and want to part of hacktoberfest2023, I'm a beginner, I spend my whole day understanding this code, and made these smaill changes, please accept my contribution. 
Thank you. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ravi0900** [comment]
@gewenyu99, please assign this to me and add hacktoberfest label, and please accept this PR.

**Comment by ravi0900** [comment]
![image](https://github.com/appwrite/website/assets/65914575/2f32d010-e8c6-4ed1-9a0c-1724d1dd9528)

**Comment by Haimantika** [comment]
Hi, thanks for raising the issue, but we are following sentence case and not title case. Appreciate your interest in contributing to Appwrite, if you are eager to learn more, join us on Discord - https://appwrite.io/discord

**Comment by ravi0900** [comment]
> Hi, thanks for raising the issue, but we are following sentence case and not title case. Appreciate your interest in contributing to Appwrite, if you are eager to learn more, join us on Discord - https://appwrite.io/discord

@Haimantika, sure I have pinged you in discord as well, trust me title case are best and also updated github star count. help me If I could improve more.

**Comment by ravi0900** [comment]
@Haimantika mam please accept it, 5 days already passed and I have not made a single PR merge yet. guide me what more I could improve in website.

**Comment by gewenyu99** [comment]
@ravi0900 Hi, please don't spam us, thank you!

We do not take certain PRs because we believe they fundamentally don't align with our goals and style guides :D

Thanks you!
