### ISSUE TITLE
📚 Documentation: docker-compose.yml and .env file for appwrite 1.4.4 are missing in docs

### ISSUE THREAD

**Issue by trashcoder** [appwrite/website#204]
### 💭 Description

In appwrite.io docs -> self hosting -> Manual (Docker Compose) the links to the docker-compose.yml and .env files are missing.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@trashcoder, thanks for raising this issue! 🙏🏼 Since we already have https://github.com/appwrite/appwrite/issues/6367, I'm going to close this as a duplicate.
