### ISSUE TITLE
🚀 Feature: Updating the colour on hover (All cards)

### ISSUE THREAD

**Issue by Smartmind12** [appwrite/website#218]
### 🔖 Feature description

Currently on hover over cards the highlight of the card selected in not visible as the colour scheme of light grey border in light theme and very dark grey border on black theme is not visible.   

A. Dark theme: As you can see below the cursor is hovered on 'self-hosted' but the shadow of hover is minimal that it cannot be distinguished from other cards which are not hovered at.

![Screenshot 2023-10-08 at 10 56 31 AM](https://github.com/appwrite/website/assets/91927689/eca253bd-2839-48ec-8907-496a6e342fca)

B. Light theme: As you can see below the cursor is hovered on 'firebase' but the shadow of hover is minimal that it cannot be distinguished from other cards which are not hovered at.

![Screenshot 2023-10-08 at 11 04 45 AM](https://github.com/appwrite/website/assets/91927689/efbec908-fbf8-4335-87ce-66da37ac9a1d)

### 🎤 Pitch

I propose to use "Apprwrite Pink" as either a background colour or outline colour on hovering over cards. 

A. Adding Background colour on hovering on top of the card:

![Screenshot 2023-10-08 at 11 13 57 AM](https://github.com/appwrite/website/assets/91927689/d0b97469-507c-4777-986f-e30405736077)

B. Adding Outline colour on hovering on top of the card:

![Screenshot 2023-10-08 at 11 10 55 AM](https://github.com/appwrite/website/assets/91927689/337e22ad-0088-4135-ac76-88aa090918aa)

I request the admins to reivew both option and finalize on the one to be use and assign this issue to me so that i can implement the desired effect.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by pratistha-05** [comment]
@Smartmind12 please assign this issue to me so that i can start working on this

**Comment by Smartmind12** [comment]
> @Smartmind12 please assign this issue to me so that i can start working on this
Hey @pratistha-05 i am currently waiting fir this issue to be assigned to me…Kindly take up and open issue!

**Comment by stnguyen90** [comment]
Thanks for raising this! Unfortunately, we don't want to add this at the moment. If you wish to contribute as part of Hacktoberfest, please look for issues labeled "hacktoberfest".
