### ISSUE TITLE
📚 Documentation: Wrong Navigation in Migration documentation

### ISSUE THREAD

**Issue by Smartmind12** [appwrite/website#231]
### 💭 Description

Wrong navigation leading to confusion of the user what the page is really about. As seen in the screenshots:
1. When user clicks 'From Cloud' - he wants to migrate from cloud to self hosted while the docs are showing 'migrate from self hosted' to a cloud instance.
2. When user clicks 'From Self-hosted' - he wants to migrate from self hosted to cloud instance while the docs are showing 'migrate from cloud' to a self hosted instance.

![Screenshot 2023-10-11 at 8 30 38 PM](https://github.com/appwrite/website/assets/91927689/8d9cea8b-fe63-46d1-9025-f795b0cae4c7)

![Screenshot 2023-10-11 at 8 33 07 PM](https://github.com/appwrite/website/assets/91927689/ceb86f87-4d36-449b-9882-546aceeef85a)

Proposing -  Updating the navigation and rewriting the headers to avoid confusion for all users.

Please assign this issue to me to update the same.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DhairyaMajmudar** [comment]
@stnguyen90 can you pls. assign me this issue.

**Comment by Smartmind12** [comment]
Hey @Khalid-212 @DhairyaMajmudar I have already asked for this issue to be assigned to me …kindly look into other open issues!

**Comment by Haimantika** [comment]
Thanks @Smartmind12 for bringing this issue up. I have raised a PR to fix this :)

**Comment by Smartmind12** [comment]
Hey @Haimantika the issue still persist since your PR just changed the headers while once the user clicks on 'from cloud' on navigation bar they want a page for migrate "from cloud to self hosted" but if you go through the docs its still a page "from self-hosted to cloud"

![Screenshot 2023-10-21 at 9 13 44 AM](https://github.com/appwrite/website/assets/91927689/637730e6-8672-4a55-bea4-77bde205459d)

**Comment by Smartmind12** [comment]
@Haimantika Please give me the opportunity to work on this and rectify the same!
