### ISSUE TITLE
📚 Documentation: Navigation not visible on specific range of view widths

### ISSUE THREAD

**Issue by Larkify** [appwrite/website#244]
### 💭 Description

The new docs have some issues with the navigation menu showing.
More specifically, view widths between 1023 < x < 1280, there is neither a hamburger menu or a sidenav visible.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by chenparnasa** [comment]
Hey @Larkify! Thank you for raising this issue! I'll bring this up with our engineers and we will fix this ASAP 🙂

**Comment by Larkify** [comment]
I tried looking at the code myself for Hacktoberfest but saw there was no breakpoint variable set that will work. I’ll take another look and if I can contribute I’ll put it in this issue 🙂

**Comment by TGlide** [comment]
#238 fixes this :)

**Comment by TGlide** [comment]
> I tried looking at the code myself for Hacktoberfest but saw there was no breakpoint variable set that will work. I’ll take another look and if I can contribute I’ll put it in this issue 🙂

No worries, a small fix is already in the works 😄  Thank you for raising the issue!
