### ISSUE TITLE
📚 Documentation: Add Docker Command to Run Project Locally

### ISSUE THREAD

**Issue by Saurav-Pant** [appwrite/website#250]
### 💭 Description

Here in the readme, only the "pnpm" command is provided for running this locally.
However, I believe that adding a **Docker** command to it would be a valuable addition. 
If you agree, please assign this task to me, as I am eager to work on it.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
> ### 💭 Description
> Here in the readme, only the "pnpm" command is provided for running this locally. However, I believe that adding a **Docker** command to it would be a valuable addition. If you agree, please assign this task to me, as I am eager to work on it.
> 
> ### 👀 Have you spent some time to check if this issue has been raised before?
> * [x]  I checked and didn't find similar issue
> 
> ### 🏢 Have you read the Code of Conduct?
> * [x]  I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

This Readme is only for the website repo. I don't see the need of adding Docker command here.

**Comment by Haimantika** [comment]
Closing this issue, as it is not relevant for the website repo.
