### ISSUE TITLE
📚 Documentation: Scroll on right menu

### ISSUE THREAD

**Issue by fliitor** [appwrite/website#253]
### 💭 Description

It's impossible to scroll on right menu with some screen size
On [this page](https://appwrite.io/docs/references/cloud/server-nodejs/databases) for ex, with 1750x700
Need to reduce with to display burger menu, and have scrolling enable

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Rohithk2003** [comment]
if the issue is valid can i work on it ?

**Comment by stnguyen90** [comment]
@fliitor, thanks for raising this issue! 🙏🏼 what exactly is the problem? Why do you need to scroll right?

**Comment by gewenyu99** [comment]
https://github.com/appwrite/website/assets/29069505/c9bdd7e6-7dac-4ef3-98c4-897d4770e1cd

You beat me to it 😄

**Comment by gewenyu99** [comment]
@stnguyen90 The right-hand menu is not scrollable

**Comment by elad2412** [comment]
This issue was solved :-)

https://appwrite.io/docs/references/cloud/server-nodejs/databases
