### ISSUE TITLE
🐛 Bug Report: Homepage of website & doc are freezy

### ISSUE THREAD

**Issue by fliitor** [appwrite/website#254]
### 👟 Reproduction steps

Refresh this page and try to click on link, or scroll page. need to wait some seconds before (cause JS Thread ?)
From [Discord](https://discord.com/channels/564160730845151244/1163514807132110878) (with examples)

### 👍 Expected behavior

Be able to click on link or scroll directly after DOM was loaded

### 👎 Actual Behavior

Need to wait

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by mqshaikh8** [comment]
This issue seems to only happen on windows and not on mac. I don't know if this is addressed, but I can look into this
https://github.com/appwrite/website/assets/46161085/738debe1-c65e-4a79-8056-e08e4069e4de

**Comment by sourabpramanik** [comment]
@adityaoberai @Haimantika @TGlide anyone working on this or can I take it?

**Comment by TGlide** [comment]
> @adityaoberai @Haimantika @TGlide anyone working on this or can I take it?

This has since been solved!
