### ISSUE TITLE
📚 Documentation: Platform Server>Rest select Client>Rest

### ISSUE THREAD

**Issue by fliitor** [appwrite/website#256]
### 💭 Description

When choice `Server>Rest` it select `Client>Rest` cause Server>Rest is last element on `Client `part

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by HridoyHazard** [comment]
can you explain the issue plz?

**Comment by fliitor** [comment]
@HridoyHazard You can check [here](https://discord.com/channels/564160730845151244/1164168054742200410)

**Comment by Haimantika** [comment]
> @HridoyHazard You can check [here](https://discord.com/channels/564160730845151244/1164168054742200410)

As it has been discussed on Discord, tagging @TGlide to take a look at it

**Comment by HridoyHazard** [comment]
hi i'm not in that discord channel so can't see it. can you invite me plz?

**Comment by Haimantika** [comment]
> hi i'm not in that discord channel so can't see it. can you invite me plz?

https://appwrite.io/discord

**Comment by HridoyHazard** [comment]
so the issue was duplicate rest button ?

**Comment by TGlide** [comment]
Fixed by #255
