### ISSUE TITLE
🐛 Bug Report:  The Vue.js logo is larger in size compared to the others

### ISSUE THREAD

**Issue by Nishantjain10** [appwrite/website#260]
### 👟 Reproduction steps

"When I visit https://appwrite.io/docs/tutorials, the Vue logo has mismatched height and width compared to logos of other frameworks, the aspect ratio of other cards is also affected.

### 👍 Expected behavior

The logo should have the same width and height as the other logos!
![image](https://github.com/appwrite/website/assets/89480234/0e7b7f68-f6d9-4c15-b868-88374fac6df3)

### 👎 Actual Behavior

![image](https://github.com/appwrite/website/assets/89480234/f464a44a-e6ab-4dee-b9ca-c61f44f84659)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

## I would like to work on this! 🍀

**Comment by Haimantika** [comment]
<img width="1512" alt="Screenshot 2023-10-18 at 7 22 12 PM" src="https://github.com/appwrite/website/assets/32809211/a1a10521-e248-4166-8d4b-906faf7ee4cd">
Looks fine to me 🤔

**Comment by Nishantjain10** [comment]
Weird, Not sure, why this happened!
