### ISSUE TITLE
📚 Documentation: Tutorials page skips from <h2> to <h4> [a11y][TheA11y100]

### ISSUE THREAD

**Issue by GrahamTheDevRel** [appwrite/website#280]
## Issue
On the tutorials page the heading levels skip from `<h2>` to `<h4>`.

![Headings Map showing skipped heading levels from h2 to h4](https://github.com/appwrite/website/assets/121672086/e4629ffe-44e7-4dad-beeb-2c144db60277)

## Why it matters
People using assistive technology rely on proper headings structure to navigate effectively. By skipping levels people can get lost or miss entire sections of content using assistive tech.

## Suggested fix
Two options here: first is to change the `<h4>` on each card to a `<h3>`.

However there is also a `<h2>` called "client" which is not currently needed / is redundant. **A better option** may be to remove this `<h2>` and promote the current cards' `<h4>`s to `<h2>`s as this will be a more logical structure for the page.

![screenshot of current page with a heading level 2 called "client" and then heading level 4s for each item](https://github.com/appwrite/website/assets/121672086/30a0183f-9eef-435b-a907-447a29df772c)

## Relevant Success Criterion WCAG
[Info and Relationships in WCAG](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships)
[Technique using heading levels](https://www.w3.org/WAI/WCAG21/Techniques/html/H42)

## Additional Notes
Good first issue, but needs input from Appwrite to which solution they would prefer.

[Found on stream on 2023-10-25](https://www.twitch.tv/videos/1959992199)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by bL34cHig0** [comment]
May I be assigned to this please?

**Comment by CBID2** [comment]
> May I be assigned to this please?
Lol, I was just about to volunteer. :) Can I work on this? :) Accessibility is my jam and I love @GrahamTheDevRel! :) Hehe, that rhymed! :)
