### ISSUE TITLE
📚 Documentation: Social Icon Labels need improving [a11y][TheA11y100]

### ISSUE THREAD

**Issue by GrahamTheDevRel** [appwrite/website#281]
## Issue
The icons for socials in the footer are incorrectly labelled as "Appwrite on aw-icon-discord".

![Discord icon in footer highlighted with corresponding element shown in dev tools, aria-label shows "Appwrite on aw-icon-discord" instead of "Discord"](https://github.com/appwrite/website/assets/121672086/06f5b0f5-c0c5-42d7-a18d-0c0a50a0abf0)

## Why it matters
People navigating via assistive tech such as a screen reader or via voice control (i.e. Dragon Natural Speaking) may be confused by the label.

## Suggested fix
Update the label to read as "Discord", "GitHub", "X App" etc.

**Important note:** Just use the name of the social, without "Appwrite". This can make navigation via voice a lot easier as they may use a command "click button discord" for example and this may not always function correctly if it starts with the text "Appwrite".

## Relevant Success Criterion WCAG
[Link Purpose (In Context)](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html)

## Additional Notes
On stream it was mentioned that this has a fallback mechanism, so the fallback mechanism may also need updating or improving to avoid this issue in the future. Up to Appwrite to advise.

[Found on stream on 2023-10-25](https://www.twitch.tv/videos/1959992199)

@jasonetorres was interested in fixing this one.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by codingmickey** [comment]
Hey @GrahamTheDevRel! can I fix this one? Or is it already decided for @jasonetorres?

**Comment by CBID2** [comment]
Can I work on this issue @GrahamTheDevRel? Please? :)

**Comment by jasonetorres** [comment]
Sorry everyone I claimed a couple I think I’m tagged in ! Plenty more up for grabs though!

**Comment by CBID2** [comment]
> Sorry everyone I claimed a couple I think I’m tagged in ! Plenty more up for grabs though!

Ok @jasonetorres.

**Comment by jasonetorres** [comment]
hey @TorstenDittmann if I could get this assigned I will go ahead and make the appropriate corrections, as a fallback issue, please advise!

**Comment by Susmita-Dey** [comment]
Hey, I'd like to take up this issue.

**Comment by Arayanmemon** [comment]
@GrahamTheDevRel Can you assign this issue to me?

**Comment by TGlide** [comment]
@jasonetorres Assigned to you 😄
