### ISSUE TITLE
📚 Documentation: Search button behind header at certain resolutions

### ISSUE THREAD

**Issue by GrahamTheDevRel** [appwrite/website#282]
## Issue
At certain screen sizes (for example 1260px width) the search button in the side menu is obscured by the header.

![Screenshot showing search button highlighted using DevTools but it is not visible as it is behind the header](https://github.com/appwrite/website/assets/121672086/446d6cd1-1385-4f66-9e5b-289d130b89a1)

## Why it matters
It is not usable currently for people using touch and mouse and is confusing for keyboard users.

## Suggested fix
Adjust the layout so the left menu is pushed down enough so the button is visible.

## Additional Notes
[Found on stream on 2023-10-25](https://www.twitch.tv/videos/1959992199)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Susmita-Dey** [comment]
Hey @stnguyen90 Can you me assign me this issue? I'd like to work on it

**Comment by TGlide** [comment]
@Susmita-Dey assigned!

**Comment by MohammedAslam106** [comment]
Hey, is it fixed or not?

**Comment by Satakshijain** [comment]
Can I work on this issue if it is not fixed

**Comment by stnguyen90** [comment]
Unassigning @Susmita-Dey due to inactivity.

@GrahamTheDevRel is this still a problem? This is what I see now:

<img width="1316" alt="image" src="https://github.com/appwrite/website/assets/1477010/c69b47db-6e50-4a5c-86de-63540b08518b">
