### ISSUE TITLE
📚 Documentation: CODE OF CONDUCT file is missing 

### ISSUE THREAD

**Issue by Susmita-Dey** [appwrite/website#300]
### 💭 Description

I expected a file like this [CODE OF CONDUCT](https://github.com/EddieHubCommunity/BioDrop/blob/main/CODE_OF_CONDUCT.md) file in this repository for contributors which is currently missing in this repository.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Susmita-Dey** [comment]
Assign this issue to me. I'll add

**Comment by adityaoberai** [comment]
Hi @Susmita-Dey 
We have an [org-wide Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md) that can be accessed through the repo too

Therefore, adding an additional Code of Conduct file to the repo would be redundant

![image](https://github.com/appwrite/website/assets/31401437/1cc9b410-5808-48b5-ad66-5515c1cb3792)

**Comment by adityaoberai** [comment]
If this solves your concern, we can close the issue.

**Comment by Haimantika** [comment]
Closing this issue as org-wide CoC exists.
