### ISSUE TITLE
📚 Documentation: Encryption has a typo

### ISSUE THREAD

**Issue by jelopez03** [appwrite/website#307]
### 💭 Description

![image](https://github.com/appwrite/website/assets/4776661/70d0318c-d571-462a-a1ea-bf9f6a69a6ff)

There is a typo on the following url:
https://appwrite.io/docs/products/storage/buckets#encryption

Thanks.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rajesh604** [comment]
hi @jelopez03 can i work on this issue
