### ISSUE TITLE
🐛 Bug Report: Missing how to uninstall previous versions of Appwrite in documentation 

### ISSUE THREAD

**Issue by Haimantika** [appwrite/website#312]
### 👟 Reproduction steps

Go [here](https://appwrite.io/docs/advanced/self-hosting#uninstall) you will expect the documentation to uninstall Appwrite, but it is not present currently.

### 👍 Expected behavior

Uninstall documentation

### 👎 Actual Behavior

Missing Unistall documentation

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Arindam200** [comment]
Can I Work on this?

**Comment by Haimantika** [comment]
Closing this issue, as the documentation is there.
