### ISSUE TITLE
📚 Documentation: Incorrect Hyperlink Destination in Storage Documentation

### ISSUE THREAD

**Issue by Arindam200** [appwrite/website#326]
## Description

In the Documentation of Storage, there is an issue with the hyperlink labeled "[Learn about file input](https://appwrite.io/docs/storage#file-input)." 

Although the link text indicates that it should point to "https://appwrite.io/docs/storage#file-input," it actually redirects to "https://appwrite.io/docs/storage" without the expected "#file-input" anchor identifier.

![image](https://github.com/appwrite/website/assets/109217591/cf44b22a-f6c1-41d5-b076-f8a2846add55)

The problem is that the "#file-input" section does not exist in the destination page, which leads to a broken link and could potentially confuse users looking for information about file input in the Storage documentation.

This issue should be addressed by either fixing the link to correctly point to the intended section with the "#file-input" anchor or by ensuring that the section is added to the Storage documentation to match the link's target.

## Steps to reproduce the issue:

Visit the page with the hyperlink: [Storage Documentation](https://appwrite.io/docs/storage#file-input).
Click on the "[Learn about file input](https://appwrite.io/docs/storage#file-input)" link.

## Expected result:

The link should navigate to the "file-input" section within the Storage documentation.

## Actual result:

The link redirects to the general Storage documentation page without the "#file-input" section.

![image](https://github.com/appwrite/website/assets/109217591/d7fcbbf9-19fb-4337-9a84-dc757f8564ef)

This issue impacts the user experience and should be resolved to ensure accurate and consistent navigation within the documentation.

-> And I want to work on this

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Thanks for raising this issue @Arindam200. Will work on it!

**Comment by sourabpramanik** [comment]
@Haimantika If this issue is still unresolved then I would like to work on it.
