### ISSUE TITLE
📚 Documentation: Id is used in incorrect way.

### ISSUE THREAD

**Issue by RahulPonnuru** [appwrite/website#332]
### 💭 Description

In this documentation of react tutorial (https://appwrite.io/docs/tutorials/react/step-7)
This specific part of code (line no 37) the id used is wrong way
 <button
       type="button"
        onClick={() =>
         ideas.add({ userId: user.current.id, title, description })
      }
>

![image](https://github.com/appwrite/website/assets/98414565/e8d0b8eb-7825-47d0-9c31-8f194b62a763)

**It should be like**
userId: user.current.$id

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Good catch! Thanks for raising this issue. I have opened a PR fixing it :)

**Comment by Haimantika** [comment]
Closing as it has been merged
