### ISSUE TITLE
🐛 Bug Report: No Focus Style on quick start button 

### ISSUE THREAD

**Issue by ketanbaitule** [appwrite/website#360]
### 👟 Reproduction steps

1. Go To https://appwrite.io/docs

![image](https://github.com/appwrite/website/assets/111437670/05b9b095-400e-4689-b474-637bf31731ef)

2. Select Follow and press tab
3. No Visual Effect on focus on quick start button

### 👍 Expected behavior

Should show some kind of outline like this

![image](https://github.com/appwrite/website/assets/111437670/6ef14281-f784-4d9c-8564-c83b420e60b5)

### 👎 Actual Behavior

Does not show

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by harmanbatheja15** [comment]
I want to work on this issue.

**Comment by harmanbatheja15** [comment]
Solved the issue and opened the pull request. Please review it.
