### ISSUE TITLE
📚 Documentation: Showing Kotlin Code with a Java Option in Selection

### ISSUE THREAD

**Issue by iammohan01** [appwrite/website#388]
### 💭 Description

When i looking realtime docs, in this [page](https://appwrite.io/docs/apis/realtime),
There are some few sample's for JavaScript, Swift and some other languages.

But When i check for **Java**, it's showing **kotlin** code, 

Screenshots attached below .

<img width="854" alt="image" src="https://github.com/appwrite/website/assets/85432311/a465debe-7580-4cd5-98a0-489e4fc28a8e">

<img width="1728" alt="image" src="https://github.com/appwrite/website/assets/85432311/2681c3eb-ffe0-4396-ae3c-a7dc56fa7176">

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by iammohan01** [comment]
I just made a pull request for this. [link](https://github.com/appwrite/website/pull/389)

**Comment by Haimantika** [comment]
Thanks @iammohan01, for both raising the issue and the PR.
