### ISSUE TITLE
📚 Documentation: Website is missing info about rate limits

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/website#395]
### 💭 Description

The previous version of the docs showed the rate limits for endpoints that had them. The new website should too.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by CBID2** [comment]
Is this the page in the docs that you're referring to @stnguyen90: https://appwrite.io/docs/advanced/platform/rate-limits

I want to work on this but I need more context.

**Comment by stnguyen90** [comment]
Rate limits are added now: 
<img width="1292" alt="image" src="https://github.com/appwrite/website/assets/1477010/be77dc84-e0bd-4010-a272-29fef5452c91">
