### ISSUE TITLE
🐛 Bug Report: Let's Encrypt Cert Issuance / HTTPS for default docker-compose.yml

### ISSUE THREAD

**Issue by zdanl** [appwrite/website#401]
### 👟 Reproduction steps

docker-compose up -d

### 👍 Expected behavior

As in docker/production.yml HTTPs should be ready and if there is no certificate, it should be issued by Let's Encrypt

### 👎 Actual Behavior

HTTP only; No certificate issuance; and if you invoke docker/production.yaml, It tries to pull a docker image from somewhere 

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Would appreciate if someone fixed the .yaml file so that the local version of the website gets deployed and Let's Encrypt is invoked on secureport

This is for the landing page and accurate docs expansion of an Appwrite Fork

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by zdanl** [comment]
Generated the Cert Chain with Let's Encrypt by hand and simply removed 443 and secure from the default Docker Compose. Then nginx proxy_pass to 127.0.0.1:80

**Comment by stnguyen90** [comment]
@zdanl, thanks for raising this issue! 🙏🏼 Unfortunately, there's no need to add SSL to this because it is not needed locally, which is the only place contributors need to use it.
