### ISSUE TITLE
🐛 Bug Report: Responsive Design Breaks on Appwrite Heroes Page for Mobile Devices.

### ISSUE THREAD

**Issue by Nishantjain10** [appwrite/website#402]
### 👟 Reproduction steps

While visiting the **appwrite.io/heroes** page the responsiveness is breaking down on mobile screens due to marquee image carousel/scroll carousel animation, in the website page. You can see clearly see overflow, by vertically scrolling on mobile devices. 

Steps to see the responsiveness bug: 
- Open a mobile browser and navigate to the [appwrite.io/heroes](https://appwrite.io/heroes) page.

- Notice the marquee image collage animation on the website.
- Vertically scroll on the mobile device to explore the content.
- You can see the point where the responsiveness breaks down or the overflow issue occurs.

### 👍 Expected behavior

- The appwrite.io/heroes page should be responsive on mobile screens.
- The scroll carousel animation should not cause overflow issues, and the content should be comfortably viewable on mobile devices.

### 👎 Actual Behavior

I think, from what I've seen, I think this happened due to max-content width within the global class of scroll carousel. 

<img src="https://github.com/appwrite/website/assets/89480234/054fb658-ae81-49be-8231-824ff5f29a79"  width="50%" height="">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

## **🛠️ Note: I am interested in working on this issue and would like to contribute a fix.**

**Comment by amrahs02** [comment]
I want to work on this issue.

**Comment by DH-555** [comment]
Looks like this is fixed by this?
https://github.com/appwrite/website/commit/1fce8f9b8cf37b1b3e2aeade79c92c8bb1b6aba6

**Comment by Nishantjain10** [comment]
> Looks like this is fixed by this? [1fce8f9](https://github.com/appwrite/website/commit/1fce8f9b8cf37b1b3e2aeade79c92c8bb1b6aba6)

Yes, you're right, @stnguyen90. I just wanted to let you know that I’ll be closing this issue now.  
Here’s the replicated issue: [#481](https://github.com/appwrite/website/pull/481). Thanks!
