### ISSUE TITLE
📚 Documentation: Contact-us Link and Redirect Loop

### ISSUE THREAD

**Issue by Anthony01M** [appwrite/website#419]
### 💭 Description

Upon attempting to access the "contact us" link at https://appwrite.io/assets#contact-us, users are unexpectedly redirected to https://appwrite.io/. Additionally, when trying to access https://appwrite.io/docs/getting-started-for-server, a redirect loop occurs, leading back to the same URL instead of redirecting to the intended destination at https://appwrite.io/docs/quick-starts.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by TheOjasSingh** [comment]
Hello, it appears that the issue mentioned earlier has already been resolved. Could you please close the issue?
