### ISSUE TITLE
Star on Github needs to be updated

### ISSUE THREAD

**Issue by amanr-dev** [appwrite/website#421]
In the website's navbar, the "star on Github" count needs to be updated from 37.9k to 38.5k.

**Comment by alex-k-exe** [comment]
Could this be made automatic by instead fetching the data with the Github API?
I could work on it but it would be my first contribution so it'll take a while

**Comment by TGlide** [comment]
We have an open PR for it: https://github.com/appwrite/website/pull/414

**Comment by amanr-dev** [comment]
I've just checked and it appears that the numbers in the community route need to be updated.

![Screenshot 2023-12-18 202249](https://github.com/appwrite/website/assets/124811276/6bc7e9ed-51d1-46cc-b4f4-ee3e7fabd76d)

**Comment by amanr-dev** [comment]
I can fix this, so can I work on this?

**Comment by TGlide** [comment]
> I can fix this, so can I work on this?

As I said, we already have an open PR for it. It has not yet been merged, so you will only see the changes later. Thank you for raising the issue though 😄

**Comment by amanr-dev** [comment]
> > I can fix this, so can I work on this?
> 
> As I said, we already have an open PR for it. It has not yet been merged, so you will only see the changes later. Thank you for raising the issue though 😄

Thanks 😅

**Comment by amanr-dev** [comment]
Hi @TGlide, this seems to be fixed. On the website, GH stars are updated.

**Comment by TGlide** [comment]
> Hi @TGlide, It seems like the issue has been resolved. On the website, GH stars are updated.

Since the process of updating stars is not yet automated, this will be a recurring issue. So instead of opening new issues for this in the future, it's better to keep it open until the relevant PR is merged 🙂

**Comment by amanr-dev** [comment]
> > Hi @TGlide, It seems like the issue has been resolved. On the website, GH stars are updated.
> 
> Since the process of updating stars is not yet automated, this will be a recurring issue. So instead of opening new issues for this in the future, it's better to keep it open until the relevant PR is merged 🙂

Now I understand. 👍.

**Comment by stnguyen90** [comment]
Issue for automating: https://github.com/appwrite/website/issues/187
