### ISSUE TITLE
🐛 Bug Report: Broken website after I created new column for Array of String in db

### ISSUE THREAD

**Issue by step135** [appwrite/website#431]
### 👟 Reproduction steps

```
Uncaught (in promise) TypeError: n[0][n[1].key] is undefined
    Immutable 89
    <anonymous> https://cloud.appwrite.io/console/project-***/databases/database-***/collection-***/document-***/data:159
    promise callback* https://cloud.appwrite.io/console/project-***/databases/database-***/collection-***/document-***/data:158

[attributeItem.36fe7338.js:1:32995](https://cloud.appwrite.io/_app/immutable/chunks/attributeItem.36fe7338.js)

```

### 👍 Expected behavior

I should see data in database, but the page is broken

### 👎 Actual Behavior

It throws error and doesn't load the page.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Closing as this is no longer a problem.
