### ISSUE TITLE
🐛 Bug Report: Broken page with server error on Chrome

### ISSUE THREAD

**Issue by step135** [appwrite/website#496]
### 👟 Reproduction steps

Version 90.0.4430.212
![screenshot](https://github.com/appwrite/website/assets/47241203/1fd49d4e-3ac7-4219-89c4-d18f9be22f6f)

### 👍 Expected behavior

Styled, no server error

### 👎 Actual Behavior

not styled, writing server error

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by step135** [comment]
The same problem in Firefox 88.0.1 (May 5, 2021)

**Comment by step135** [comment]
`ReferenceError: structuredClone is not defined`

**Comment by stnguyen90** [comment]
@step135, thanks for raising this issue! 🙏🏼 It looks like Chrome 90.0.4430.212 was released May 2021, making it over 2 years old. Why should we add support for that version?

**Comment by stnguyen90** [comment]
Closing as stale.
