### ISSUE TITLE
🚀 Feature: Enhance Default Scrollbar Appearance with Custom Styling. 

### ISSUE THREAD

**Issue by suraj-py** [appwrite/website#532]
### 🔖 Feature description

Enhance how the website's scrollbar looks by adding a custom design that perfectly fits the unique style of the Appwrite Website, making it more visually appealing.

### 🎤 Pitch

Enhancing the scrollbar with custom styling tailored to Appwrite Website's theme isn't just above aesthetics, it's a strategic move to elevate user experience. This thoughtful customization not only aligns with our brand identity but also adds a touch of sophistication, making navigation more engaging. By implementing this feature, we not only reinforce our commitment to design excellence but also ensure a cohesive and visually pleasing interface, fostering a positive impression among users. It's a small yet impactful detail that contributes significantly to the overall user satisfaction and perception of our platform.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by VedangSardessai** [comment]
Hello @stnguyen90 Can you me assign me this issue? I'd like to work on it.

**Comment by TheOjasSingh** [comment]
Hi @stnguyen90 can you assign me this issue?

**Comment by EVDOG4LIFE** [comment]
Hi, thanks for submitting @suraj-py!

We'll need more information on this, as the current experience is in line with the design of the site. If you still believe this enhancement is necessary, please reopen the issue with as much detail as possible.

Details should include, but not limited to:

* The specific aspects of the current scrollbar design that you think could be improved.
* How your proposed design changes would better align with the Appwrite website's aesthetic and user experience goals.
* Any examples or precedents of similar design implementations that have positively impacted user engagement or satisfaction.
* If possible, mockups or design concepts of your proposed scrollbar design.

This will help us evaluate the suggestion more thoroughly and consider its alignment with our overall design strategy and user experience objectives. We appreciate your contribution and look forward to potentially revisiting this with more detailed information.
