### ISSUE TITLE
📚 Documentation: Update website copy, misspelling 

### ISSUE THREAD

**Issue by tessamero** [appwrite/website#579]
### 💭 Description

"annoymous" should be "anonymous" under the "Secure login for all users" section.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by hdhaliwa** [comment]
@tessamero and @Haimantika  I raised the PR https://github.com/appwrite/website/pull/672/commits/2c2f5b974227ea62e02b417d0492beb4d194f1ba

Please review and approve. Thanks
