### ISSUE TITLE
Update License Copyright

### ISSUE THREAD

**Issue by dipanshurdev** [appwrite/website#595]
In README.md, the License copyright year needs to be updated.

![Screenshot 2024-02-09 212523](https://github.com/appwrite/website/assets/124811276/ba4eed35-60b9-43ae-8855-c90c76ada4c7)

**Comment by mathanraj0601** [comment]
I would like to work on this issue @amanr-dev  can I get assigned?

**Comment by amanr-dev** [comment]
Assigned it to @mathanraj0601

**Comment by mathanraj0601** [comment]
Thank you @amanr-dev :). I have made a PR for this issue can you review it
