### ISSUE TITLE
📚 Documentation:  Vue.js Quick start example uses undefined function 'createEmailPasswordSession'

### ISSUE THREAD

**Issue by FernandoABava** [appwrite/website#724]
### 💭 Description

Hi,
I was trying to test appwrite for the first time using vue.js and I couldn't get the 'quick start' tutorial working. In the console there was an error pointing out that `account.createEmailPasswordSession` was undefined. I couldn't get more information about this in the documentation so I console logged the `account` object until I found the `account.createEmailSession` function. The tutorial code is now working, so I guess it is just an error in the documentation. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
createEmailPasswordSession is correct now
