### ISSUE TITLE
Documentation: Wrong Info. on Environment Variables in Tutorials

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/website#745]
### 💭 Description

Similar to one of the old issue - appwrite/appwrite#6417, the linked documentations use `({}).`.

Verified by using Private / Incognito Modes on Safari & Chrome, not sure if these are just cached.

Links that have this issue -
1. https://appwrite.io/docs/tutorials/nuxt/step-3#init-sdk
2. https://appwrite.io/docs/tutorials/astro-ssr-auth/step-3
3. https://appwrite.io/docs/tutorials/nextjs-ssr-auth/step-3

However, the docs seem correct for these links.
1. https://github.com/appwrite/website/blob/main/src/routes/docs/tutorials/nuxt/step-3/%2Bpage.markdoc
2. https://github.com/appwrite/website/blob/main/src/routes/docs/tutorials/astro-ssr-auth/step-3/%2Bpage.markdoc
3. https://github.com/appwrite/website/blob/main/src/routes/docs/tutorials/nextjs-ssr-auth/step-3/%2Bpage.markdoc

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ItzNotABug, is this still a problem?

**Comment by ItzNotABug** [comment]
@stnguyen90 Doesn't seem to be an issue anymore.
