### ISSUE TITLE
📚 Documentation: Broken Link for `Refine - Live Provider` In Tutorials

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/website#746]
### 💭 Description

The tutorial here - https://appwrite.io/docs/tutorials/refine/step-5#blog-context references a link to https://refine.dev/docs/api-reference/core/live-provider/ which leads to a `404`.

The correct link could be - https://refine.dev/docs/realtime/live-provider/

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by TheOjasSingh** [comment]
Hi @eldadfux I want to work on this issue.

**Comment by reetbatra** [comment]
looks like this is fixed :)

**Comment by ItzNotABug** [comment]
Closing as this seems fixed. Thanks for the update @reetbatra!
