### ISSUE TITLE
📚 Documentation: SvelteKit tutorial is buggy

### ISSUE THREAD

**Issue by SumitBando** [appwrite/website#764]
### 💭 Description

https://appwrite.io/docs/tutorials/sveltekit/step-7 shows code for src/routes/+page.svelte, which has:

```javascript
	import { user } from '$lib/user.js';
```

This leads to runtime error:

```json
{
    "name": "AppwriteException",
    "code": 401,
    "type": "general_unauthorized_scope",
    "response": {
        "message": "User (role: guests) missing scope (account)",
        "code": 401,
        "type": "general_unauthorized_scope",
        "version": "0.12.111"
    }
}
```
presumably because the because the page assumes the user is logged in.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@SumitBando, thanks for raising this issue! 🙏🏼 Is something breaking? Where exactly are you seeing an error? It's expected for the console logs to show a 401 error if the user isn't logged in because the browser will always log HTTP calls that result in a status code of 400 or higher.
