### ISSUE TITLE
📚 Documentation: Queries tutorial

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/website#77]
### 💭 Description

Appwrite Databases has many different query methods.

While we have this page: `/docs/products/databases/queries`, but this is a reference, not a tutorial. There are also not enough examples.

## Goal
Interactive examples in a tutorial format to introduce Apwrite's many query methods.

## Content
1. Server SDK/CLI script to set up an example database with test data.
2. A page with one or many examples for each query method.
3. Written in Node.js
4. Added to `src/routes/docs/tutorials`

## How to contribute
Pitch an outline detailing each page you plan to add and headings within, and ask to be assigned. Open a PR **after** the outline has been approved.

The Appwrite team will collaborate with you on the outline and PR.

Thanks for taking the time to make our documentation better 🙏

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Susmita-Dey** [comment]
Hey @gewenyu99 I wanna take up this issue. Kindly assign it to me.

Here's an outline of the tutorial guide:
-

**Comment by Haimantika** [comment]
> Hey @gewenyu99 I wanna take up this issue. Kindly assign it to me.
> 
> Here's an outline of the tutorial guide:
> 
> * Introduction
>   
>   * Brief overview of Appwrite's query methods.
> * Setting Up Example Database
>   
>   * Provide code snippets to set up a sample database using Server SDK/CLI script.
> * Query Methods Examples
>   
>   * Method 1: Query Method 1 Explanation
>     
>     * Example code in Node.js.
>     * Explanation of the example.
>   * Method 2: Query Method 2 Explanation
>     
>     * Example code in Node.js.
>     * Explanation of the example.
>   * Other methods and examples in the same way

Hi, this issue is not a part of hacktoberfest.

**Comment by Susmita-Dey** [comment]
Hey @Haimantika I know that. I just want to contribute.

**Comment by gewenyu99** [comment]
@Susmita-Dey You know what, we can make this part of Hacktoberfest. It was removed because it was a large scope that could be too difficult. But I know you've been in our community for a long time and have experience. I'll let you have a go and mark it for Hacktoberfest, too!

Lmk if you need help, this one might be tough!

Feel free to post frequent updates!

**Comment by soumwadeep** [comment]
Can I Also Contribute In It?

**Comment by soumwadeep** [comment]
My Outline Will Go Like This
Introduction
- Brief overview of Appwrite Databases query methods
- How to use query methods to filter, sort, and paginate results
- Different types of query methods available
- Benefits of using query methods

Setting Up Example Database

- Code snippets to set up a sample database using Server SDK/CLI script
- Creating a database
- Creating a collection
- Inserting some test data

Query Methods Examples

Method 1: equal()

- Explanation of the equal() method
- Example code in Node.js
- Explanation of the example

Method 2: notEqual()

- Explanation of the notEqual() method
- Example code in Node.js
- Explanation of the example

Method 3: lessThan()

- Explanation of the lessThan() method
- Example code in Node.js
- Explanation of the example

Please Assign Me If Possible @Haimantika @gewenyu99

**Comment by soumwadeep** [comment]
@Haimantika Can I Be Assigned?

**Comment by gewenyu99** [comment]
@soumwadeep This has already been assigned, we assign on a first come first server basis :D

**Comment by soumwadeep** [comment]
ok sir

**Comment by Susmita-Dey** [comment]
Update: Work in progress

**Comment by shivanshu814** [comment]
Can I Also Contribute In It? @gewenyu99

**Comment by tessamero** [comment]
@Susmita-Dey do you plan to continue to work on your draft PR? Please send a follow up so the PR doesn't get closed. =]
