### ISSUE TITLE
📚 Documentation:  typo in "send email messages" docs

### ISSUE THREAD

**Issue by jasonetorres** [appwrite/website#778]
### 💭 Description

[Schedule emails](https://appwrite.io/docs/products/messaging/send-email-messages#schedule-emails)

What is there: To send an scheduled email, you can call the createEmail endpoint with status set 

What should be there: To send a (remove the N) scheduled email, you can call the createEmail endpoint with status set 

![Screenshot 2024-03-10 at 6 06 34 AM](https://github.com/appwrite/website/assets/110337114/d5276d60-d502-4367-84c5-8fa231dcd800)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Fixed at #779
