### ISSUE TITLE
📚 Documentation: Appwrite upgrade breaks Docker Compose stack ownership

### ISSUE THREAD

**Issue by ericswpark** [appwrite/website#797]
### 💭 Description

If you try and upgrade Appwrite with the documentation found here: https://appwrite.io/docs/advanced/self-hosting/update , you'll run into an error like the following:

```
Error response from daemon: Conflict. The container name "/appwrite-assistant"
is already in use by container "123456...". You have to remove (or rename) that
container to be able to reuse that name.
```

~~Please add a step to spin down the Docker Compose stack. Maybe before this sentence:~~

~~"The first step is to install the latest version of Appwrite. Head to the directory where you ran your previous Appwrite install command."~~

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ericswpark, what were you upgrading from and to? Did you make any other modifications outside of the [install with docker](https://appwrite.io/docs/advanced/self-hosting#install-with-docker)? Docker should be able to pick up the change in the compose file and stop the old container and bring up the new container. Same goes for the network. 🧐

**Comment by ericswpark** [comment]
@stnguyen90 I was upgrading from 1.4.13 (or the last patch version) to 1.5.2 or .3 (the one where the console error was fixed), although I think I also encountered the issue going to 1.5.2 as well. I didn't make any modifications to the base `docker-compose.yml` file, but I did add my backend service with the `docker-compose.overrides.yml` file. You can check it out here: https://github.com/Purdue-CS307-tsundoku/tsundoku/blob/main/docker/docker-compose.override.yml

As you can see the overrides file just defines a new `overrides` network, and patches `traefik` in the original `docker-compose.yml` so that it's not running on ports 80 and 443, as that is where the NginxProxyManager is running.

Yes, it is weird that Docker doesn't pick up the changes. I think I had it work _once_ when trying a migration to 1.5.1 but that one failed because of an Appwrite DB issue that was patched in 1.5.2.

**Comment by stnguyen90** [comment]
@ericswpark, whoa! I didn't know about the [`!reset` tag](https://docs.docker.com/compose/compose-file/13-merge/#reset-value)! Thanks for that insight!

Let's see if anyone else runs into this too.

**Comment by ericswpark** [comment]
I just had a thought. On the host side, the folder housing the Docker Compose configuration file is named `docker/`. I've been using the following command to upgrade:

```
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/docker:/usr/src/code/appwrite:rw \
    --entrypoint="upgrade" \
    appwrite/appwrite:1.5.4
```

Notice the folder name `appwrite/` replaced with `docker/`.

Docker Compose uses the parent directory name to set the stack prefix. I'm wondering if this is the cause of the bug -- the Appwrite container just spins up the stack under the `appwrite/` prefix, since that is what is exposed to the Appwrite Docker image.

**Comment by stnguyen90** [comment]
@ericswpark, hmm yes, weird things can happen if you use something different like that. For your case, you might want to avoid spinning up the stack inside the upgrade container by using the `--no-start=true` flag like:

```
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/docker:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:1.5.4 --no-start=true
```

This will skip the `docker compose up` inside the container:

https://github.com/appwrite/appwrite/blob/f0ee1926bee2768e0a284ae07d5b3f41aa4d2c31/src/Appwrite/Platform/Tasks/Install.php#L226-L229

 and then you can run it manually on your host.

**Comment by ericswpark** [comment]
@stnguyen90 great, thanks. Maybe this can be noted in the documentation? I'll submit a pull request if I can find the time. For now I'll keep this issue open for anybody that might encounter the problem too.

**Comment by stnguyen90** [comment]
Some additional context and why this happens:

Docker uses a project name to group containers, networks, volumes, etc. in a docker-compose.yml file. This is how docker knows what containers you're talking about when you do something like `docker compose down`. 

By default, [the project name is the folder](https://docs.docker.com/compose/project-name/#set-a-project-name) where the docker-compose.yml file is in.

So, when you use the install command:

```
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:1.5.4
```

The full path in the container is `/usr/src/code/appwrite` and so the folder name is `appwrite`. If you don't use `appwrite` as the folder name on your host machine, and you try to run `docker compose` commands on your host machine, docker will think it's a new/different project.

**Comment by ericswpark** [comment]
Yup, I usually set the `DOCKER_COMPOSE_PROJECT` environment variable for my other projects that use DC, but I think the best solution would be to just warn the user in the documentation and let them run the stack manually. @stnguyen90 I've made those changes in #861, can you please take a look? Thank you!

**Comment by stnguyen90** [comment]
Honestly, I'd rather people not rename the folder and stick with the default folder name instead. These different variations can cause unforeseen side effects like this or the upgrade command not working, etc. That said, we've opened up a discussion internally on how to proceed.
