### ISSUE TITLE
📚 Documentation: Tutorial for Next JS

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/website#80]
### Goal
Interactive tutorial for beginners to build their first functioning app using Next.js and Appwrite.

### Content
1. The end product should be a functional app
2. Step by step from setup. If there will be test data, provide a Server SDK script with instructions.
3. Format should be similar to ` /docs/tutorials/sveltekit`
4. Should contain the following content
    1. install dependencies
    2. make first request 
    3. implement auth
    4. intro to databases
    5. queries and paginations
    6. storage (optional)
    7. realtime (optional)
    8. permissions (optional)

### How to contribute
Pitch an outline detailing each page you plan to add and headings within, and ask to be assigned. Open a PR **after** the outline has been approved.

The Appwrite team will collaborate with you on the outline and PR.

Thanks for taking the time to make our documentation better 🙏

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Vishalk91-4** [comment]
@gewenyu99, @Haimantika 
I would like to work on this issue
Please assign it to me

**Comment by Mridul2820** [comment]
I would like to work on this. Can you assign it to me?

**Comment by Haimantika** [comment]
> Hi @gewenyu99 , I would like to work on this. Can you assign it to me?

Hi @Mridul2820 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Mridul2820** [comment]
Sure @Haimantika Will do that :)

**Comment by Mridul2820** [comment]
Hi @Haimantika , I have created a Tutorial for Next JS in the docs and also raised a PR #80

**Comment by Haimantika** [comment]
> Hi @Haimantika , I have created a Tutorial for Next JS in the docs and also raised a PR #80

We have a PR review party on Discord today. Please join us there and share your PR link, will review it then.

**Comment by Tushar98644** [comment]
@Haimantika I would like to work on this issue if the current assignee is not working

**Comment by PrinceSah09** [comment]
Hii @gewenyu99, @Haimantika :),

I very excited to work on this issue, please assign it to me.

**Comment by tessamero** [comment]
Closing issue as the PR was merged, great job!
