### ISSUE TITLE
📚 Documentation: The link to the `demos-for-react` repository on the last page of the `nextjs-ssr-auth` tutorial is broken

### ISSUE THREAD

**Issue by bybruno** [appwrite/website#802]
### 💭 Description

The link [demos-for-react](https://github.com/appwrite/demos-for-react/tree/main/nextjs/server-side-rendering) on the page https://appwrite.io/docs/tutorials/nextjs-ssr-auth/step-8 redirects to a non-existent file. 

![image](https://github.com/appwrite/website/assets/33330711/becba005-e759-4bfb-88c6-aaeac5079d6d)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by mthirumalai2905** [comment]
Yes i faced the same issue here

**Comment by Ayush9026** [comment]
I will solve this issue.

**Comment by stnguyen90** [comment]
Depends on https://github.com/appwrite/demos-for-react/pull/28
