### ISSUE TITLE
📚 Update Heading from Community Events

### ISSUE THREAD

**Issue by dipanshurdev** [appwrite/website#813]
At the `/community` page, change the heading from **Upcoming Events** to **Recent Events** or something contrary to Upcoming.
### screenshot
![Screenshot 2024-03-22 121352](https://github.com/appwrite/website/assets/124811276/241631ca-c45c-4991-b267-cc9c6fe31fb9)

**Comment by stnguyen90** [comment]
@dipanshurdev, thanks for creating this issue! 🙏🏼 We've updated the events now:
![image](https://github.com/user-attachments/assets/f68dd212-5ca1-45fb-9e19-062b8a37f4aa)
