### ISSUE TITLE
🚀 Enhancement: Please add a dynamic footer

### ISSUE THREAD

**Issue by mthirumalai2905** [appwrite/website#824]
### 🔖 Enhancement description

![Screenshot (243)](https://github.com/appwrite/website/assets/98790479/843e1128-0163-4a2c-8d52-fb7683b7e726)
![Screenshot (242)](https://github.com/appwrite/website/assets/98790479/99b8026c-8db5-4cd0-81c1-e9830d2b3861)

### 🎤 Pitch

Please add a dynamic footer since hard coding footer is not a good practice

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by EVDOG4LIFE** [comment]
Hello! Thanks for opening this.

The Footer is actually Dynamic, see here: https://github.com/appwrite/website/blob/main/src/lib/components/MainFooter.svelte#L27

Year is defined by `const year = new Date().getFullYear()`.
