### ISSUE TITLE
Using your website

### ISSUE THREAD

**Issue by abd3lraouf** [appwrite/website#840]
Can I use your website on my domain without all the content it has?
Am I allowed to? just trying to understand [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/).

**Comment by stnguyen90** [comment]
@abd3lraouf, what exactly are you trying to use?

**Comment by abd3lraouf** [comment]
> @abd3lraouf, what exactly are you trying to use?

Thank you @stnguyen90 I mean just like using it like any hugo theme for example

**Comment by abd3lraouf** [comment]
> @abd3lraouf, what exactly are you trying to use?

Thank you @stnguyen90 I mean just like using it like any hugo theme for example

**Comment by stnguyen90** [comment]
@abd3lraouf, our website isn't a hugo theme, though. We plan to update [Pink](https://pink.appwrite.io/) in the near future, so maybe you can use that to build your website in the future.

**Comment by abd3lraouf** [comment]
> @abd3lraouf, our website isn't a hugo theme, though. We plan to update [Pink](https://pink.appwrite.io/) in the near future, so maybe you can use that to build your website in the future.

Yes I know it's not a hugo theme, so I meant if I can use your web application in my website, just will remove all of your content.

The question is:
- can I do so?
- If yes, then am I allowed to use my own changes without your permission as I'm going to add some features specific to my usecase
-
