### ISSUE TITLE
🐛 Bug Report: View Event Button not disabling when event date has passed

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [appwrite/website#860]
### 👟 Reproduction steps

- We need to add logic to determine whether the event date has passed. This can be done by comparing the event date with the current date.
- Depending on whether the event has completed or not, we need to update the state of the button accordingly. If the event has completed, the button should be disabled and labeled as `Event Completed`. Otherwise, it should remain enabled with the label `View Event`.
- We'll make the necessary changes to the `EventCard.svelte` component to incorporate the logic.

### 👍 Expected behavior

The button should be disabled and labeled **Event Completed** if the event date has passed.

### 👎 Actual Behavior

Currently, in the event card component, the button intended to be disabled and labeled **Event Completed** if the event date has passed is not functioning as expected. Despite the event date being hardcoded and already passed, the button still displays **View Event** and remains enabled.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gewenyu99** [comment]
PR: https://github.com/appwrite/website/pull/924
