### ISSUE TITLE
🚀 Enhancement: Add All Products on Footer

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/website#865]
### 🔖 Enhancement description

Footer Nav shows only - Auth, Databases, Functions, Storage, Realtime.
Products on Docs show - Auth, Databases, Functions, Messaging, Storage, AI, Realtime (in APIs).

---
I am open to contributing to this issue if required.

### 🎤 Pitch

Add all the products in the Footer Nav.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gewenyu99** [comment]
Added messaging. AI at the moment is not a real product ;) yet... so closing this for now :)
<img width="223" alt="Screenshot 2024-04-25 at 11 58 12 AM" src="https://github.com/appwrite/website/assets/29069505/3930f4c9-c6c6-4524-afcc-df1b29998a6c">
