### ISSUE TITLE
🚀 Enhancement: Enhance README with Social Media Links and Icons

### ISSUE THREAD

**Issue by Ayush9026** [appwrite/website#904]
### 🔖 Enhancement description

The current README of the Appwrite repository includes some social media links but lacks icons for platforms like YouTube, LinkedIn etc. Adding these icons will enhance the visual appeal and usability of the README, making it easier for users to connect with Appwrite on various social platforms.

### 🎤 Pitch

1.Review and update existing social media links in the README.
2.Add missing social media links for platforms like YouTube, LinkedIn, Twitter, etc.
3.Include corresponding social media icons for each link to improve visual representation.
4.Ensure all links and icons are correctly formatted and functional.
5.Test the links to verify they direct users to the correct social media profiles.

Upon completion of these tasks, the README of the Appwrite repository will have consistent and clickable social media icons linked to the respective platforms, providing users with easy access to connect with Appwrite on social media.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Ayush9026, thanks for creating this issue! 🙏🏼 For now, we'd prefer not to clutter the readme with that information.
