### ISSUE TITLE
🚀 Enhancement: Add Dark and Night Mode Toggle Button to Appwrite Website

### ISSUE THREAD

**Issue by Ayush9026** [appwrite/website#907]
## Description:
As users increasingly prefer dark and night mode interfaces for improved readability and reduced eye strain, it would be beneficial to implement a toggle button on the Buildpack website that allows users to switch between light and dark modes seamlessly. This feature would enhance the user experience and align with modern design trends.

### 🎤 Pitch

This enhancement would contribute positively to user satisfaction and engagement with the Appwrite website.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gewenyu99** [comment]
@Ayush9026 Appwrite's website is mode-less.

While we have modes for pages like Docs that are focus on experience and readability, the website itself combines both light and dark mode concepts.

Closing for now :)
