### ISSUE TITLE
🚀 Enhancement: Add Appwrite Cloud Status Section with Live Availability and Downtime Graph

### ISSUE THREAD

**Issue by Ayush9026** [appwrite/website#908]
### 🔖 Enhancement description

We propose adding an "Appwrite Cloud Status" section to the website, featuring a live graph that displays the availability and downtime of the Appwrite cloud infrastructure. This feature will provide users with real-time insights into the platform's performance and ensure transparency regarding system status.

### 🎤 Pitch

**Implementation Plan:**

1. Design: Collaborate with designers to create a visually appealing and informative section for the website, integrating a live graph for availability and downtime tracking.

2. Development: Implement the live graph functionality using JavaScript libraries or frameworks to fetch and display real-time data on system status.

3. Testing: Conduct thorough testing to ensure the accuracy and reliability of the live graph, simulating various scenarios to validate its functionality.

4. User Interaction: Enable users to click on the graph to access detailed information about specific downtime incidents, providing a seamless and interactive experience.

**Benefits:**

Enhances transparency: Users can easily monitor Appwrite's cloud status and stay informed about any disruptions or maintenance activities.
Improves user experience: Interactive features like clickable graphs offer a user-friendly way to access detailed system status information.
Builds trust: Demonstrates Appwrite's commitment to transparency and reliability, fostering trust among users and stakeholders.

[
![Appwrite web](https://github.com/appwrite/website/assets/114745463/5e61e2a8-6572-49c2-8c56-b045c8702191)
](url)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by sagarhedaoo** [comment]
Hi @Ayush9026 Can you assign this to me, I can make this enhancement in the Footer!

**Comment by DH-555** [comment]
Looks like this is already implemented with better uptime.
