### ISSUE TITLE
🚀 Enhancement: Truncate or Show Shorter Content on Search

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/website#916]
### 🔖 Enhancement description

Current doc search items shows as much as content possible, doesn't really look nice.

See -
<img width="722" alt="Screenshot 2024-04-25 at 2 34 07 PM" src="https://github.com/appwrite/website/assets/20625965/067422c8-ece0-4c22-97d1-836e2b425e34">

### 🎤 Pitch

Show something shorter like -

![appwrite io_docs](https://github.com/appwrite/website/assets/20625965/5dc5bd62-1ce5-49d1-9413-059826d102e9)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gewenyu99** [comment]
Taking a look with @elad2412

**Comment by gewenyu99** [comment]
The text wrapping is also not right here, will fix that too.
