### ISSUE TITLE
📚 Documentation: Deep dive authentication recipe with Android

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/website#93]
### Goal
Deep dive tutorial for beginners to learn Appwrite Authentication in depth with Android.

### Content
1. The end product should be a functional app with auth screens.
2. Step by step from setup. If there will be test data, provide a Server SDK script with instructions.
3. Format should be similar to ` /docs/tutorials/sveltekit`
4. Should contain the following content
      1. Sign up
      1. Log in
      1. Verification
      1. Recovery
      1. Conditional routing based on auth state
      1. Preferences
      1. Delete account

### How to contribute
Pitch an outline detailing each page you plan to add and headings within, and ask to be assigned. Open a PR **after** the outline has been approved.

The Appwrite team will collaborate with you on the outline and PR.

Thanks for taking the time to make our documentation better 🙏

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by poseidon2060** [comment]
Hey I would love to work on this issue since I was just learning and using Appwrite Auth for a personal project, I think this issue can be perfect for me since I can learn and teach at the same time
However I didn't understand the format for the PR (` /docs/tutorials/sveltekit`)
Can someone please elaborate on that

**Comment by Haimantika** [comment]
> Hey I would love to work on this issue since I was just learning and using Appwrite Auth for a personal project, I think this issue can be perfect for me since I can learn and teach at the same time
> However I didn't understand the format for the PR (` /docs/tutorials/sveltekit`)
> Can someone please elaborate on that

By format we mean that the style of writing will be same as the sveltekit tutorials.

**Comment by anwarpro** [comment]
Hey, I would love to work on this issue. Last week I tried implementing the Android client SDK  in Compose multiplatform project.

**Comment by Haimantika** [comment]
> Hey I would love to work on this issue since I was just learning and using Appwrite Auth for a personal project, I think this issue can be perfect for me since I can learn and teach at the same time
> However I didn't understand the format for the PR (` /docs/tutorials/sveltekit`)
> Can someone please elaborate on that

Hi @poseidon2060 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Haimantika** [comment]
> Hey, I would love to work on this issue. Last week I tried implementing the Android client SDK in Compose multiplatform project.

Hi, we are assigning issues on first-come first-serve basis, if Pawan is unresponsive, will assign it to you!

**Comment by Haimantika** [comment]
Hi @poseidon2060 are you still working? If not, will reassign the issue to the next person

**Comment by letsintegreat** [comment]
Hey, I would like to be assigned if the current assignee is unresponsive, thanks!

**Comment by Haimantika** [comment]
> Hey, I would love to work on this issue. Last week I tried implementing the Android client SDK in Compose multiplatform project.

Hi, would you still like to work on it?

**Comment by anwarpro** [comment]
> > Hey, I would love to work on this issue. Last week I tried implementing the Android client SDK in Compose multiplatform project.
> 
> Hi, would you still like to work on it?

Yes

**Comment by Haimantika** [comment]
> > > Hey, I would love to work on this issue. Last week I tried implementing the Android client SDK in Compose multiplatform project.
> > 
> > 
> > Hi, would you still like to work on it?
> 
> Yes

Assigning it to you

**Comment by CharithaCS** [comment]
Hi @Haimantika, I'd love to take up this issue in case the Assignee is unresponsive.

**Comment by anwarpro** [comment]
> > > > Hey, I would love to work on this issue. Last week I tried implementing the Android client SDK in Compose multiplatform project.
> > > 
> > > 
> > > Hi, would you still like to work on it?
> > 
> > 
> > Yes
> 
> Assigning it to you

I'm working on this.
![ideatracker](https://github.com/appwrite/website/assets/47409922/d5f91fbc-885a-4993-aeaa-ba2aaad9377c)

**Comment by tessamero** [comment]
Closing this issue as hacktoberfest is now over. Thank you to everyone who participated this year :)
