### ISSUE TITLE
📚 Documentation: Cover banner not visible on README

### ISSUE THREAD

**Issue by Satarupa22-SD** [appwrite/website#942]
### 💭 Description

The cover banner is not visible on README file, I think the link for the banner needs to be updated. 
<img width="1440" alt="Screenshot 2024-05-02 at 9 46 30 PM" src="https://github.com/appwrite/website/assets/84276219/cf8ace9f-6c61-4b89-ac30-cec930bda6a3">

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Satarupa22-SD** [comment]
If this issue is approved, I would like to take this up. I would be grateful if the maintainers could let me know which logo/image should be used for the banner. Thanks :)

**Comment by Ayush9026** [comment]
Hi @Satarupa22-SD ,

Thank you for reporting this issue. I have checked and can confirm that the cover banner is visible on my laptop and smartphone as well. It seems like the problem might be specific to certain devices or configurations.

To troubleshoot this further, could you please provide more information about the device and browser you are using where the cover banner is not visible? This will help us investigate and address the issue more effectively.

Looking forward to your response.

**Comment by Satarupa22-SD** [comment]
@Ayush9026 Thank you for your response. I am currently using MacBook Pro M2 and safari as my browser.

**Comment by Satarupa22-SD** [comment]
@Ayush9026 I just checked again with my smartphone, it is visible. I am sorry for the inconveniences caused.  I think last night the logo might not have been visible due to the internet connectivity. I am closing this issue. Sorry 😐.

**Comment by Ayush9026** [comment]
No worries,  @Satarupa22-SD . It happens! Glad to hear that the issue seems to have resolved itself. Remember, open source is all about collaboration. Have a great day!
