### ISSUE TITLE
📚 Documentation: Add GitHub Organizations to Appwrite README

### ISSUE THREAD

**Issue by Ayush9026** [appwrite/website#953]
### 💭 Description

Currently, the Appwrite README lacks information about our GitHub organizations, which are crucial for understanding our team structure, project management, and collaboration on GitHub. This issue aims to add a section to the README that provides details about our GitHub organizations.

**Proposed Changes:**

Section Addition
List of Organizations
Link to GitHub
Formatting

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Ayush9026, thanks for creating this issue! 🙏🏼 For now, we'd prefer not to clutter the readme with that information.
