### ISSUE TITLE
🚀 Enhancement: adding rss feed to blog

### ISSUE THREAD

**Issue by LimaneGaya** [appwrite/website#974]
### 🔖 Enhancement description

An rss feed to the blog section of the website

### 🎤 Pitch

it's a good way to keep people updated on the latest and greatest of Appwrite, it's a common way every other providers use to keep interested users updated.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
Doesn't one exist already?
https://appwrite.io/blog/rss.xml

**Comment by LimaneGaya** [comment]
Yes but i seems to not show in correct format i can see in the code and in #337 that it should work, but my [rss reader](https://feeder.co) does not find it and going to https://appwrite.io/blog/rss.xml show up like follows:

<details closed><summary>appwrite.io/blog/rss.xml</summary>

```xml
Appwrite https://appwrite.io Appwrite is an open-source platform for building applications at any scale, using your preferred programming languages and tools. Appwrite Decoded: Dylan Graham Tue, 04 Jun 2024 00:00:00 GMT https://appwrite.io/blog/post/appwrite-decoded-dylan https://appwrite.io/blog/post/appwrite-decoded-dylan In this blog, we hear from our finance and operations lead, Dylan Graham. Integrate any external authentication solution into your Appwrite project Thu, 30 May 2024 00:00:00 GMT https://appwrite.io/blog/post/integrate-custom-auth-sveltekit https://appwrite.io/blog/post/integrate-custom-auth-sveltekit Add any custom authentication flow to your applications. Integrate SQL, NoSQL, Vector, Graph, or any database into your Appwrite project Fri, 24 May 2024 00:00:00 GMT https://appwrite.io/blog/post/integrate-sql-nosql-vector-graph-or-any-database-into-your-appwrite-project https://appwrite.io/blog/post/integrate-sql-nosql-vector-graph-or-any-database-into-your-appwrite-project With databases it's always "it depends", but we got the answers. Building the future of language learning for over 5000 users worldwide with LangX Thu, 23 May 2024 00:00:00 GMT https://appwrite.io/blog/post/case-study-langx https://appwrite.io/blog/post/case-study-langx Learn how LangX used Appwrite to develop an open-source language exchange platform similar to Tandem and support thousands of learners all around the world. Introducing the Python machine learning runtime Tue, 21 May 2024 00:00:00 GMT https://appwrite.io/blog/post/introducing-python-machine-learning-runtime https://appwrite.io/blog/post/introducing-python-machine-learning-runtime A new runtime optimized for machine learning workloads, now available in Appwrite Cloud. Build a personal chatbot with GPT-4o and Appwrite Functions Fri, 17 May 2024 00:00:00 GMT https://appwrite.io/blog/post/personal-chatbot-gpt-4o https://appwrite.io/blog/post/personal-chatbot-gpt-4o Learn how to use OpenAI's new flagship model, GPT-4o to create an intelligent chatbot. Building with Appwrite AI Function templates Thu, 16 May 2024 00:00:00 GMT https://appwrite.io/blog/post/building-with-ai-function-templates https://appwrite.io/blog/post/building-wit
```

</details>
I tried it locally and it works well, maybe it's not in prod yet?

**Comment by ItzNotABug** [comment]
I can see an xml, however its malformed. Probably the reason its not available in the feed apps.

@TorstenDittmann Some characters seem to break the xml. Checked via - https://validator.w3.org/feed/

**Comment by ItzNotABug** [comment]
Can I be assigned to work on this?

**Comment by Meldiron** [comment]
@ItzNotABug Sure thing! 🙌 Assigned to you

**Comment by TorstenDittmann** [comment]
The markup is valid, however - a title seem to have broken the and needs to be sanitized before rendering it into XML.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fappwrite.io%2Fblog%2Frss.xml
