### ISSUE TITLE
📚 Documentation: Small typo in the Appwrite vs Firebase blog

### ISSUE THREAD

**Issue by Haimantika** [appwrite/website#975]
### 💭 Description

In the resources section of the [Appwrite vs Firebase blog](https://appwrite.io/blog/post/open-source-firebase-alternative), there is an `e` missing in `Appwrite YouTube`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by adityaoberai** [comment]
Ah thanks a lot for raising this @Haimantika! I'll fix it :)
