### ISSUE TITLE
📚 Documentation: Typo in the Security section of the docs/products/auth/email-password Page

### ISSUE THREAD

**Issue by adipundir** [appwrite/website#999]
### 💭 Description

The section Says : 
Appwrite's security first mindset goes beyond a securely implemented ~of~ authentication API.

removing the "of" is required.
Appwrite's security first mindset goes beyond a securely implemented authentication API.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by adipundir** [comment]
i will be able to fix this if assigned to me.

**Comment by stnguyen90** [comment]
@adipundir, assigned! Thanks for your interest! 🙏🏼
